title: Tasty D
email: tastyminerals@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about learning the D programming language and various D language trivia.
baseurl: "/tasty-blog" # the subpath of your site, e.g. /blog
url: "tasty-blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tastyminerals
github_username: tastyminerals
github_repo:  tastyminerals/tasty-blog

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude: ["vendor"]

category_dir: categories
